//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public address()
        {
            this.companyinfoes = new HashSet<companyinfo>();
            this.customers = new HashSet<customer>();
            this.staffs = new HashSet<staff>();
        }
    
        public int id { get; set; }
        public string buildingname { get; set; }
        public string houseno { get; set; }
        public string street { get; set; }
        public string locality { get; set; }
        public string postaltown { get; set; }
        public string country { get; set; }
        public Nullable<int> postcode_id { get; set; }
    
        public virtual postcode postcode { get; set; }
        public virtual ICollection<companyinfo> companyinfoes { get; set; }
        public virtual ICollection<customer> customers { get; set; }
        public virtual ICollection<staff> staffs { get; set; }
    }
}
