//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class logininfo
    {
        public Nullable<System.DateTime> lastlogindate { get; set; }
        public Nullable<bool> lockedout { get; set; }
        public Nullable<int> cumulativefailures { get; set; }
        public Nullable<System.DateTime> registerdate { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public int user_id { get; set; }
        public string user_userid { get; set; }
    
        public virtual user loginuser { get; set; }
    }
}
