//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordermaster
    {
        public ordermaster()
        {
            this.orderchilds = new HashSet<orderchild>();
        }
    
        public int id { get; set; }
        public string ticketno { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public string customercode { get; set; }
        public string paymentstatus { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> discountamount { get; set; }
        public Nullable<decimal> deliverycharge { get; set; }
        public Nullable<decimal> grandtotal { get; set; }
        public string server { get; set; }
        public Nullable<decimal> paidamount { get; set; }
        public string paytype { get; set; }
        public Nullable<int> printreceiptcopies { get; set; }
        public int servicetype_id { get; set; }
    
        public virtual ICollection<orderchild> orderchilds { get; set; }
        public virtual servicetype servicetype { get; set; }
    }
}
