//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class permission
    {
        public permission()
        {
            this.securitygrouppermissions = new HashSet<securitygrouppermission>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<securitygrouppermission> securitygrouppermissions { get; set; }
    }
}
