//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Datamodel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POSDB : DbContext
    {
        public POSDB()
            : base("name=POSDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<address> addresses { get; set; }
        public DbSet<companyinfo> companyinfoes { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<department> departments { get; set; }
        public DbSet<logininfo> logininfoes { get; set; }
        public DbSet<menu> menus { get; set; }
        public DbSet<orderchild> orderchilds { get; set; }
        public DbSet<ordermaster> ordermasters { get; set; }
        public DbSet<permission> permissions { get; set; }
        public DbSet<postcode> postcodes { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<productbutton> productbuttons { get; set; }
        public DbSet<productcategory> productcategories { get; set; }
        public DbSet<productingredient> productingredients { get; set; }
        public DbSet<rawstocklistchild> rawstocklistchilds { get; set; }
        public DbSet<rawstocklistmaster> rawstocklistmasters { get; set; }
        public DbSet<rawstockproduct> rawstockproducts { get; set; }
        public DbSet<securitygroup> securitygroups { get; set; }
        public DbSet<securitygrouppermission> securitygrouppermissions { get; set; }
        public DbSet<servicetype> servicetypes { get; set; }
        public DbSet<staff> staffs { get; set; }
        public DbSet<user> users { get; set; }
    }
}
