//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class productingredient
    {
        public int id { get; set; }
        public string ingredient { get; set; }
        public Nullable<bool> chargeable { get; set; }
        public Nullable<decimal> amount { get; set; }
        public int product_id { get; set; }
    
        public virtual product product { get; set; }
    }
}
