//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.orderchilds = new HashSet<orderchild>();
            this.productingredients = new HashSet<productingredient>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string receiptdescription { get; set; }
        public string status { get; set; }
        public string prepproduct { get; set; }
        public string preplocation { get; set; }
        public Nullable<decimal> buyingprice { get; set; }
        public Nullable<decimal> dineinprice { get; set; }
        public Nullable<decimal> collectionprice { get; set; }
        public Nullable<decimal> waitingprice { get; set; }
        public Nullable<decimal> deliveryprice { get; set; }
        public Nullable<decimal> allprice { get; set; }
        public string stockproduct { get; set; }
        public Nullable<int> stockquantity { get; set; }
        public string discountable { get; set; }
        public string popupmessage { get; set; }
        public string lookupcode { get; set; }
        public Nullable<int> receiptcopies { get; set; }
        public byte[] image { get; set; }
        public int productcategory_id { get; set; }
        public int menu_id { get; set; }
    
        public virtual menu menu { get; set; }
        public virtual ICollection<orderchild> orderchilds { get; set; }
        public virtual productcategory productcategory { get; set; }
        public virtual productbutton productbutton { get; set; }
        public virtual ICollection<productingredient> productingredients { get; set; }
    }
}
