//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.users = new HashSet<user>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public Nullable<System.DateTime> dateofbirth { get; set; }
        public string designation { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> hiredate { get; set; }
        public string status { get; set; }
        public byte[] image { get; set; }
        public int department_id { get; set; }
        public int address_id { get; set; }
    
        public virtual address address { get; set; }
        public virtual department department { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
