//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string userid { get; set; }
        public string password { get; set; }
        public string status { get; set; }
        public int securitygroup_id { get; set; }
        public int staff_id { get; set; }
    
        public virtual logininfo logininfo { get; set; }
        public virtual securitygroup securitygroup { get; set; }
        public virtual staff staff { get; set; }
    }
}
